fix port forwading via nginx

diff --git a/kubernetes/react-backend-demo/docker/Dockerfile.client b/kubernetes/react-backend-demo/docker/Dockerfile.client
--- a/kubernetes/react-backend-demo/docker/Dockerfile.client
+++ b/kubernetes/react-backend-demo/docker/Dockerfile.client
@@ -28,8 +28,14 @@ CMD ["npm", "run", "start"]
 FROM nginx:alpine
 LABEL description="React Nginx deployment image"
 
-COPY nginx.conf /etc/nginx/nginx.conf
 COPY --from=development /client/build /var/www
-EXPOSE 80
+
+RUN if [[ ! -f "/var/www/index.html" ]]; then \
+    echo "missing production builds for the react application" && exit 1; \
+    fi
+
+COPY nginx.conf /etc/nginx/nginx.conf
+
+EXPOSE 3000
 
 CMD ["nginx","-g","daemon off;"]
